### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by whs2k** [whs2k/ImageSimilarity#1]
Noticed on Mobile; when uploading large images (like the one here) you get this error message: https://drive.google.com/open?id=1JjCZ7tZEKdpa8YVHm5kvfFm5T1R5Q2q9

Is the server big enough?

**Comment by elixir14** [comment]
Will,

The default upload size in web server was 1MB I have updated the
configuration file to 20 MB and pushed the updated configuration file to
github.

Regards,
Jitendra Sanghani
